### ISSUE TITLE
Error SSL in examples/online.py!

### ISSUE THREAD

**Issue by QuestionPython** [karthikb351/CaptchaParser#10]
hello,

examples$ python2.7 online.py
---------
```
Fetching Captcha
Traceback (most recent call last):
  File "online.py", line 18, in <module>
    r=br.open('https://academics.vit.ac.in/parent/parent_login.asp')
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 284, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_opener.py", line 195, in open
    response = urlopen(self, req, data)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 352, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1212, in https_open
    return self.do_open(conn_factory, req)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_urllib2_fork.py", line 1157, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```
how fix?

**Comment by Presto412** [comment]
`
try:
        _create_unverified_https_context=ssl._create_unverified_context
except AttributeError:
        pass
else:
        ssl._create_default_https_context=_create_unverified_https_context
print "Fetching Captcha"        

r=br.open('https://vtop.vit.ac.in/parent/parent_login.asp')`

Add this try:except block before you open the link
